spring:
  data:
    mongodb:
      database: project
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include: env, health, httptrace, metrics
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
